# Conclusion

After exploring various relationships between fare amount, tip amount, trip distance, payment type, pick up and drop off locations, and month from the 2023 NYC taxi data, there were several main takeaways. The majority of rides started and ended in Manhattan and fare increased linearly with trip distance except for in cases where there was a dispute or nothing was charged. The most trips occurred in May and October and the fewest occurred in July through September. When examining patterns in tip amount, we found that tips tended to fall between 10-20%, although there were peaks at 0%, 20%, 25%, and 30%, and there were no clear seasonal patterns evident. A main limitation was the size of the data files. While there was data available from other years, we were only able to use data from 2023 because of this. Additionally, since there were still over 38 million rows of data, we had to subsample for certain graphs to prevent overplotting. Other limitations include over 1 million missing values in 5 columns, which we handled by filtering out NA values. In the future, examining changes in the variables over the years would be an interesting avenue to explore, especially when considering the appearance of apps such as Uber and Lyft. For instance, how have these competitors affected fare amounts and ride frequency? Other questions to explore might relate to ride frequency and tip amount at different times of day. Additionally, merging this dataset with others (i.e., seasonal temperature or precipitation data, sports events or concert occurrences) could provide another angle on the patterns we observed. Overall, we learned that even within just one year of data, there were many spatial and temporal patterns to examine, and different visualizations highlighted new aspects of these patterns.

